name: Host Service CI

on:
  push:
    branches: [ "main" ]
    paths: ["*.js"] 
    # 자바 스크립트 변경 시~

jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout
        uses: actions/checkout@v3 #checkout: 소스를 내려받는 것

      - name: 2. Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: 3. Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: caroline73/hostservice:${{ github.sha }} #latest 절대 쓰면 안 됨 
  updateYaml:
    runs-on: ubuntu-latest
    needs: buildImage
    steps:
      - name: 1. Checkout
        uses: actions/checkout@v3
        with:
          repositry: 'caroline73/hostsvc-cd'
          token: ${{ secrets.GITHAB_TOKEN }}
      - name: 2. Chage Docker Tag
        run: |
          sed "s/image: caroline73\/node-app:.*/images: caroline73\/node-app:${{ github.sha }}/g"
          git config --global user.email "caroine73@naver.com"
          git config --global user.name "caroline733"
          git commit -am "triggered by github action"
          git push origin main
